name: tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: testing_database
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: xdebug

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Overwrite Database Name in phpunit.xml
        run: |
          sed -i 's/\(<server name="DB_DATABASE" value="\)[^"]*\("\/>\)/\1testing_database\2/' phpunit.xml
          sed -i 's/\(<server name="DB_USER" value="\)[^"]*\("\/>\)/\1root\2/' phpunit.xml
          sed -i 's/\(<server name="DB_PASSWORD" value="\)[^"]*\("\/>\)/\1\2/' phpunit.xml
          sed -i 's/\(<server name="DB_CONNECTION" value="\)[^"]*\("\/>\)/\1mysql\2/' phpunit.xml

      - name: Install Aspell
        shell: bash
        run: |
          sudo apt-get update && sudo apt-get install -y aspell aspell-en

      - name: Install Node Dependencies
        run: npm ci

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Publish Ziggy Configuration
        run: php artisan ziggy:generate

      - name: Build Assets
        env:
          APP_ENV: testing
          DB_CONNECTION: mysql
          DB_DATABASE: testing_database
          DB_USERNAME: root
          DB_PASSWORD: ''
        run: npm run build

      - name: Run Tests
        env:
          APP_ENV: testing
          DB_CONNECTION: mysql
          DB_DATABASE: testing_database
          DB_USERNAME: root
          DB_PASSWORD: ''
        run: ./vendor/bin/pest
